# Generated by Django 4.0 on 2022-02-06 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wtype', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('artist', models.CharField(max_length=500)),
                ('description', models.TextField(null=True)),
                ('thumbnail', models.CharField(max_length=500)),
                ('pic', models.CharField(max_length=500)),
                ('picprd', models.CharField(max_length=500)),
                ('youtube', models.CharField(blank=True, max_length=200, null=True)),
                ('wtype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.type')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('pimage', models.CharField(blank=True, max_length=500, null=True)),
                ('d_pimage', models.CharField(blank=True, max_length=500, null=True)),
                ('eng_name', models.CharField(blank=True, max_length=500, null=True)),
                ('introduce', models.TextField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('wpage', models.CharField(blank=True, max_length=500, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.work')),
            ],
        ),
    ]
