# Generated by Django 4.0 on 2022-01-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0014_alter_profile_d_pimage_alter_profile_eng_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='artist',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='work',
            name='pic',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='work',
            name='picprd',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='work',
            name='thumbnail',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
